## DL Lab - 1
- Name: Namansh Singh Maurya
- RegNo: 22MIA1034

#### Steps
- loading the dataset
- feature extraction
- MLP
- testing

# Importing Libraries

In [ ]:
import pandas as pd
import numpy as np

# Loading the Dataset

In [ ]:
df = pd.read_csv('/content/Dataset.csv')
df

Text  Label
0                            The movie is good.      1
1                             The movie is bad.      0
2  The acting skills of the actor is fantastic.      1
3      The direction and story telling is poor.      0
4                       The story is excellent.      1

In [ ]:
print(df.head())

                                           Text  Label
0                            The movie is good.      1
1                             The movie is bad.      0
2  The acting skills of the actor is fantastic.      1
3      The direction and story telling is poor.      0
4                       The story is excellent.      1


In [ ]:
t = df['Text'].values
t

array(['The movie is good.', 'The movie is bad.',
       'The acting skills of the actor is fantastic.',
       'The direction and story telling is poor.',
       'The story is excellent.'], dtype=object)

In [ ]:
l = df['Label'].values
l

array([1, 0, 1, 0, 1])

# Feature Extraction

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

v = CountVectorizer()
f = v.fit_transform(t)

v1 = TfidfVectorizer()
f1 = v1.fit_transform(t)

print(f)
print("\n")
print(f1)

  (0, 15)	1
  (0, 9)	1
  (0, 8)	1
  (0, 7)	1
  (1, 15)	1
  (1, 9)	1
  (1, 8)	1
  (1, 3)	1
  (2, 15)	2
  (2, 8)	1
  (2, 0)	1
  (2, 12)	1
  (2, 10)	1
  (2, 1)	1
  (2, 6)	1
  (3, 15)	1
  (3, 8)	1
  (3, 4)	1
  (3, 2)	1
  (3, 13)	1
  (3, 14)	1
  (3, 11)	1
  (4, 15)	1
  (4, 8)	1
  (4, 13)	1
  (4, 5)	1


  (0, 15)	0.32842677961242445
  (0, 9)	0.556074875921159
  (0, 8)	0.32842677961242445
  (0, 7)	0.689240475622327
  (1, 15)	0.32842677961242445
  (1, 9)	0.556074875921159
  (1, 8)	0.32842677961242445
  (1, 3)	0.689240475622327
  (2, 15)	0.3847515252910833
  (2, 8)	0.19237576264554165
  (2, 0)	0.40372213952983327
  (2, 12)	0.40372213952983327
  (2, 10)	0.40372213952983327
  (2, 1)	0.40372213952983327
  (2, 6)	0.40372213952983327
  (3, 15)	0.2108961275762835
  (3, 8)	0.2108961275762835
  (3, 4)	0.4425892049641061
  (3, 2)	0.4425892049641061
  (3, 13)	0.357078183796795
  (3, 14)	0.4425892049641061
  (3, 11)	0.4425892049641061
  (4, 15)	0.32842677961242445
  (4, 8)	0.32842677961242445
  (4, 13)	0.

# MLP

In [ ]:
from sklearn.neural_network import MLPClassifier

ml = MLPClassifier()
ml.fit(f1,l)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

# Testing

In [ ]:
text_t = ['The movie is bad.']
f_t = v1.transform(text_t)
ml.predict(f_t)

array([0])

### Implement the following algorithms
* SVM
* Naive Bayes
* Random Forest

## SVM

In [ ]:
from sklearn.svm import SVC
sv = SVC()
sv.fit(f1,l)

SVC()

In [ ]:
svm_output = sv.predict(f_t)
svm_output

array([0])

# Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(f1,l)

MultinomialNB()

In [ ]:
nb_output = nb.predict(f_t)
nb_output

array([1])

## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(f1,l)

RandomForestClassifier()

In [ ]:
rf_output = rf.predict(f_t)
rf_output

array([0])